# Generated by Django 2.2.4 on 2019-10-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('numero_eu', models.IntegerField()),
                ('numero_us', models.IntegerField()),
            ],
        ),
    ]
