# Generated by Django 2.2.4 on 2019-10-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.DecimalField(decimal_places=1, max_digits=3)),
                ('numero_uk', models.DecimalField(decimal_places=1, max_digits=3)),
                ('numero_us', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
    ]
