# Generated by Django 2.2.4 on 2019-10-03 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tallas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talla',
            old_name='numero_eu',
            new_name='numero_uk',
        ),
    ]
