# Generated by Django 2.2.4 on 2019-10-03 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallas', '0002_auto_20191003_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talla',
            name='numero',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='talla',
            name='numero_uk',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='talla',
            name='numero_us',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
