# Generated by Django 2.2.4 on 2019-10-07 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_cliente_contrasena'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='contrasena',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
