# Generated by Django 2.2.4 on 2019-10-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallas', '0001_initial'),
        ('zapatos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zapato',
            name='talla',
        ),
        migrations.AddField(
            model_name='zapato',
            name='talla',
            field=models.ManyToManyField(to='tallas.Talla'),
        ),
    ]
