# Generated by Django 2.2.4 on 2019-10-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapatos', '0002_auto_20191003_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapato',
            name='descripcion',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='zapato',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
