# Generated by Django 2.2.4 on 2019-10-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapatos', '0003_auto_20191003_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapato',
            name='altura_suela',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='zapato',
            name='altura_tacon',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
