# Generated by Django 2.2.4 on 2019-10-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapatos', '0004_auto_20191003_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='zapato',
            name='imagen',
            field=models.ImageField(default=None, upload_to=None),
        ),
    ]
