# Generated by Django 2.2.4 on 2019-10-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapatos', '0005_zapato_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapato',
            name='imagen',
            field=models.ImageField(upload_to=None),
        ),
    ]
