# Generated by Django 2.2.4 on 2019-10-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zapatos', '0008_zapato_imagen'),
        ('clientes', '0004_auto_20191007_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cliente', models.ManyToManyField(to='clientes.Cliente')),
                ('zapato', models.ManyToManyField(to='zapatos.Zapato')),
            ],
        ),
    ]
